# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WatchflareAgent < Formula
  desc "Watchflare host monitoring agent"
  homepage "https://watchflare.io"
  version "0.33.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/watchflare-io/watchflare/releases/download/v0.33.1/watchflare-agent_0.33.1_darwin_amd64.tar.gz"
      sha256 "5b991e72c008979c806bc604f66ea99376f05d2bebe4ab89b76e688b58a2e343"

      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/watchflare-io/watchflare/releases/download/v0.33.1/watchflare-agent_0.33.1_darwin_arm64.tar.gz"
      sha256 "01534dad6721e044f123a722a22a592852a1e49d77e79e12de54d7b40544f1d2"

      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/watchflare-io/watchflare/releases/download/v0.33.1/watchflare-agent_0.33.1_linux_amd64.tar.gz"
      sha256 "acc5c34b94782b5dc12eabbeb3d1a314f98d6bbc312fa625834b197911b02d7c"
      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/watchflare-io/watchflare/releases/download/v0.33.1/watchflare-agent_0.33.1_linux_arm64.tar.gz"
      sha256 "47cdee0502ca692eb40bd64747ab603ca3288d2692d12c46caed000b62620be3"
      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
  end

  def caveats
    <<~EOS
      Register your agent before starting the service:
        watchflare-agent-launcher register --token=YOUR_TOKEN --host=YOUR_HOST

      Then start the service:
        brew services start watchflare-agent

      To update:
        brew upgrade watchflare-agent && brew services restart watchflare-agent
    EOS
  end

  service do
    run ["#{bin}/watchflare-agent-launcher"]
    log_path "#{var}/log/watchflare-agent.log"
    error_log_path "#{var}/log/watchflare-agent.log"
    keep_alive true
    restart_delay 5
    process_type :background
  end
end
