# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WatchflareAgent < Formula
  desc "Watchflare host monitoring agent"
  homepage "https://watchflare.io"
  version "0.36.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/watchflare-io/watchflare/releases/download/v0.36.0/watchflare-agent_0.36.0_darwin_amd64.tar.gz"
      sha256 "6f38388ed272863a64c3639c975e04fc89fde5ca493a8e3e002c57fa04d7b7df"

      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/watchflare-io/watchflare/releases/download/v0.36.0/watchflare-agent_0.36.0_darwin_arm64.tar.gz"
      sha256 "8e33958c8be9aef815bbb458535f580df558a1916b8dd6a77ef2a5250eef80bb"

      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/watchflare-io/watchflare/releases/download/v0.36.0/watchflare-agent_0.36.0_linux_amd64.tar.gz"
      sha256 "61609dd15ee3b16a25c9498ddbdb0b1195fcb27f4b35fda4728bb9f3bf31c205"
      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/watchflare-io/watchflare/releases/download/v0.36.0/watchflare-agent_0.36.0_linux_arm64.tar.gz"
      sha256 "bdb8a6563572157cc0d99e6e7dfaf135bf49fad8e475537695af4ebdce8ef8d9"
      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
  end

  def caveats
    <<~EOS
      Register your agent before starting the service:
        watchflare-agent-launcher register --token=YOUR_TOKEN --host=YOUR_HOST

      Then start the service:
        brew services start watchflare-agent

      To update:
        brew upgrade watchflare-agent && brew services restart watchflare-agent
    EOS
  end

  service do
    run ["#{bin}/watchflare-agent-launcher"]
    log_path "#{var}/log/watchflare-agent.log"
    error_log_path "#{var}/log/watchflare-agent.log"
    keep_alive true
    restart_delay 5
    process_type :background
  end
end
